spring.application.name=biblioteca-api
spring.datasource.url=jdbc:h2:mem:bibliotecadb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
springdoc.swagger-ui.custom-css=/swagger-custom.css
springdoc.swagger-ui.css-url=/swagger-custom.css
springdoc.swagger-ui.custom-css-url=/swagger-custom.css